package tugas.pkg10.pbo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader; 
import java.io.BufferedWriter; 
import java.io.File; 
import java.io.FileWriter; 
import java.util.ArrayList; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel;

public class GUIMHS extends javax.swing.JFrame {
    DefaultTableModel modelMHS;
    InputMHS dataMHS;

    public GUIMHS() {
        initComponents();
        dataMHS = new InputMHS();
        viewTable();
        
    }
    
    public final void viewTable() {
    String[] namakolom = {"NIM", "Nama", "Alamat", "Mata Kuliah", "Nilai Akhir"}; 
    Object[][] objekmahasiswa = new Object[dataMHS.getAll().size()][5]; // Ubah ukuran array menjadi 5 kolom
    int i = 0; 
    for (MAHASISWA MHS: dataMHS.getAll()) {  
        Object[] arrayMahasiswa = {  
            MHS.getNIM(), 
            MHS.getNama(),  
            MHS.getAlamat(),
            MHS.getMK(), // Ambil nama mata kuliah
            MHS.getNILAIAKHIR() // Ambil nilai akhir
        }; 
        objekmahasiswa[i] = arrayMahasiswa; 
        i++; 
    } 
    modelMHS = new DefaultTableModel(objekmahasiswa, namakolom); 
    TABEL.setModel(modelMHS); 
}

    
     public void ClearTextField(){  
        NIMFIELD.setText(""); 
        NAMAFIELD.setText(""); 
        ALAMATFIELD.setText(""); 
        MKFIELD.setText("");
        NILAI1FIELD.setText("");
        NILAI2FIELD.setText("");
        NILAI3FIELD.setText("");
        NILAI4FIELD.setText("");
        NILAI5FIELD.setText("");
        NILAIAKHIRFIELD.setText("");
        NIMFIELD.requestFocus();  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        NIMFIELD = new javax.swing.JTextField();
        NAMAFIELD = new javax.swing.JTextField();
        ALAMATFIELD = new javax.swing.JTextField();
        NILAI5FIELD = new javax.swing.JTextField();
        MKFIELD = new javax.swing.JTextField();
        NILAI3FIELD = new javax.swing.JTextField();
        NILAI4FIELD = new javax.swing.JTextField();
        NILAI2FIELD = new javax.swing.JTextField();
        NILAI1FIELD = new javax.swing.JTextField();
        NILAIAKHIRFIELD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL = new javax.swing.JTable();
        NIM = new javax.swing.JLabel();
        NAMA = new javax.swing.JLabel();
        ALAMAT = new javax.swing.JLabel();
        MK = new javax.swing.JLabel();
        NILAI1 = new javax.swing.JLabel();
        NILAI2 = new javax.swing.JLabel();
        NILAI4 = new javax.swing.JLabel();
        NILAI3 = new javax.swing.JLabel();
        NILAI5 = new javax.swing.JLabel();
        NILAIAKHIR = new javax.swing.JLabel();
        SIMPAN = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();
        HITUNG = new javax.swing.JButton();

        jLabel5.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ALAMATFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALAMATFIELDActionPerformed(evt);
            }
        });

        NILAI1FIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NILAI1FIELDActionPerformed(evt);
            }
        });

        TABEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "ALAMAT", "MATA KULIAH", "NILAI AKHIR"
            }
        ));
        jScrollPane1.setViewportView(TABEL);

        NIM.setText("NIM");

        NAMA.setText("NAMA");

        ALAMAT.setText("ALAMAT");

        MK.setText("MATA KULIAH");

        NILAI1.setText("NILAI 1 [10%]");

        NILAI2.setText("NILAI 2 [15%]");

        NILAI4.setText("NILAI 4 [15%]");

        NILAI3.setText("NILAI 3 - UTS [25%]");

        NILAI5.setText("NILAI 5 [35%]");

        NILAIAKHIR.setText("NILAI AKHIR");

        SIMPAN.setText("SIMPAN");
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        HAPUS.setText("HAPUS");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        HITUNG.setText("HITUNG");
        HITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HITUNGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MK)
                                    .addComponent(ALAMAT)
                                    .addComponent(NAMA)
                                    .addComponent(NIM))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NAMAFIELD)
                                    .addComponent(NIMFIELD)
                                    .addComponent(ALAMATFIELD)
                                    .addComponent(MKFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SIMPAN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HAPUS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HITUNG)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NILAI1)
                            .addComponent(NILAIAKHIR)
                            .addComponent(NILAI5)
                            .addComponent(NILAI4)
                            .addComponent(NILAI3)
                            .addComponent(NILAI2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NILAI1FIELD)
                            .addComponent(NILAI2FIELD)
                            .addComponent(NILAI3FIELD)
                            .addComponent(NILAI4FIELD)
                            .addComponent(NILAI5FIELD)
                            .addComponent(NILAIAKHIRFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NILAI1FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIM)
                            .addComponent(NILAI1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NILAI2FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NAMA)
                                    .addComponent(NILAI2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NILAI3FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ALAMAT)))
                            .addComponent(NILAI3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NILAI4FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MK)
                            .addComponent(NILAI4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NIMFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NAMAFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ALAMATFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MKFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NILAI5FIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NILAI5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NILAIAKHIRFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NILAIAKHIR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SIMPAN)
                            .addComponent(HAPUS)
                            .addComponent(HITUNG))
                        .addGap(56, 56, 56)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALAMATFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALAMATFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALAMATFIELDActionPerformed

    private void NILAI1FIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NILAI1FIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NILAI1FIELDActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
        int selectedRow = TABEL.getSelectedRow();

        if (selectedRow >= 0) { // Memastikan ada baris yang dipilih
            // Menghapus data dari model tabel berdasarkan baris yang dipilih
            dataMHS.Hapus(selectedRow);

            // Memperbarui tampilan tabel
            viewTable();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus terlebih dahulu.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void HITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HITUNGActionPerformed
         HITUNG.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                // Mengambil input nilai 1 sampai 5 dari text field masing-masing
                double NILAI1 = Double.parseDouble(NILAI1FIELD.getText());
                double NILAI2 = Double.parseDouble(NILAI2FIELD.getText());
                double NILAI3 = Double.parseDouble(NILAI3FIELD.getText());
                double NILAI4 = Double.parseDouble(NILAI4FIELD.getText());
                double NILAI5 = Double.parseDouble(NILAI5FIELD.getText());

                // Buat objek Mahasiswa dengan nilai input dan langsung menghitung NilaiAkhir
                MAHASISWA MHS = new MAHASISWA("12345", "Nama Mahasiswa", "Alamat", "Mata Kuliah", 
                                                    NILAI1, NILAI2, NILAI3, NILAI4, NILAI5);

                // Mengambil hasil NilaiAkhir dari objek Mahasiswa
                double hasilAkhir = MHS.getNILAIAKHIR();

                // Menampilkan hasil perhitungan di txtNilaiAkhir
                NILAIAKHIRFIELD.setText(String.valueOf(hasilAkhir));

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Masukkan nilai valid pada semua kolom input nilai 1 sampai 5", "Input Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    });
    }//GEN-LAST:event_HITUNGActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        String NIM = NIMFIELD.getText();
        String Nama = NAMAFIELD.getText();
        String Alamat = ALAMATFIELD.getText();
        String MataKuliah = MKFIELD.getText();

        try {
            double NILAI1 = Double.parseDouble(NILAI1FIELD.getText());
            double NILAI2 = Double.parseDouble(NILAI2FIELD.getText());
            double NILAI3 = Double.parseDouble(NILAI3FIELD.getText());
            double NILAI4 = Double.parseDouble(NILAI4FIELD.getText());
            double NILAI5 = Double.parseDouble(NILAI5FIELD.getText());

            dataMHS.Input(NIM, Nama, Alamat, MataKuliah, NILAI1, NILAI2, NILAI3, NILAI4, NILAI5);
            viewTable(); // Refresh tabel
            ClearTextField(); // Kosongkan field input
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input nilai harus berupa angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SIMPANActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALAMAT;
    private javax.swing.JTextField ALAMATFIELD;
    private javax.swing.JButton HAPUS;
    private javax.swing.JButton HITUNG;
    private javax.swing.JLabel MK;
    private javax.swing.JTextField MKFIELD;
    private javax.swing.JLabel NAMA;
    private javax.swing.JTextField NAMAFIELD;
    private javax.swing.JLabel NILAI1;
    private javax.swing.JTextField NILAI1FIELD;
    private javax.swing.JLabel NILAI2;
    private javax.swing.JTextField NILAI2FIELD;
    private javax.swing.JLabel NILAI3;
    private javax.swing.JTextField NILAI3FIELD;
    private javax.swing.JLabel NILAI4;
    private javax.swing.JTextField NILAI4FIELD;
    private javax.swing.JLabel NILAI5;
    private javax.swing.JTextField NILAI5FIELD;
    private javax.swing.JLabel NILAIAKHIR;
    private javax.swing.JTextField NILAIAKHIRFIELD;
    private javax.swing.JLabel NIM;
    private javax.swing.JTextField NIMFIELD;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTable TABEL;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
